import os
import logging
from dotenv import load_dotenv
from openai import AsyncOpenAI
from fastapi import HTTPException, Depends
from sqlmodel import select, Session
from sqlalchemy.orm import selectinload
from utils.core.db import engine
from utils.chat.models import Document, Publication

load_dotenv(os.getenv("ENVIRONMENT", ".env"), override=True)

logger = logging.getLogger("uvicorn.error")

S3_BUCKET = os.getenv("S3_BUCKET")

# Helper function to get or create a vector store
async def get_vector_store(assistantId: str, client: AsyncOpenAI = Depends(lambda: AsyncOpenAI())) -> str:
    assistant = await client.beta.assistants.retrieve(assistantId)
    if assistant.tool_resources and assistant.tool_resources.file_search and assistant.tool_resources.file_search.vector_store_ids:
        return assistant.tool_resources.file_search.vector_store_ids[0]
    raise HTTPException(status_code=404, detail="Vector store not found")


# Helper function to generate the FILE_PATHS dictionary
def get_file_paths() -> dict[str, str]:
    """In theory you could use this at app startup in prod, but for
    faster start times, we are generating this at build time and
    storing it in the repo.

    Use like:
     `uv run python -c 'from utils.chat.files import get_file_paths; \
        import json; print(json.dumps(get_file_paths(), indent=2))'`
     to get the file paths for the documents in the database."""
    with Session(engine) as session:
        documents = session.exec(select(Document)).all()
        document_dict = {"doc_" + str(doc.id): doc.storage_url or doc.download_url for doc in documents}
        return document_dict


# Helper function to generate the DOCUMENT_CITATIONS dictionary
def get_citations() -> dict[str, str]:
    """In theory you could use this at app startup in prod, but for
    faster start times, we are generating this at build time and
    storing it in the repo.
    
    Use like:
     `uv run python -c 'from utils.chat.files import get_citations; \
        import json; print(json.dumps(get_citations(), indent=2))'`
     to get the citations for the documents in the database."""
    with Session(engine) as session:
        documents = session.exec(
            select(Document)
            .options(selectinload(Document.publication))
        ).all()
        document_dict = {"doc_" + str(doc.id): "WBG, \"" + doc.publication.title + "\", " + doc.publication.publication_date.strftime("%Y") for doc in documents if doc.publication}
        return document_dict


def cleanup_temp_file(file_path: str):
    """Removes the temporary file."""
    try:
        os.unlink(file_path)
        logger.info(f"Successfully cleaned up temporary file: {file_path}")
    except OSError as e:
        logger.error(f"Error cleaning up temporary file {file_path}: {e}")


FILE_PATHS = {
  "doc_598": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_240/doc_598.pdf",
  "doc_599": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_240/doc_599.pdf",
  "doc_600": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_241/doc_600.pdf",
  "doc_601": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_242/doc_601.pdf",
  "doc_602": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_243/doc_602.pdf",
  "doc_603": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_243/doc_603.pdf",
  "doc_604": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_244/doc_604.pdf",
  "doc_605": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_244/doc_605.pdf",
  "doc_606": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_244/doc_606.pdf",
  "doc_607": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_244/doc_607.pdf",
  "doc_608": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_245/doc_608.pdf",
  "doc_609": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_245/doc_609.pdf",
  "doc_610": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_245/doc_610.pdf",
  "doc_611": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_245/doc_611.pdf",
  "doc_612": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_245/doc_612.pdf",
  "doc_613": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_245/doc_613.pdf",
  "doc_614": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_245/doc_614.pdf",
  "doc_615": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_246/doc_615.pdf",
  "doc_473": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_201/doc_473.pdf",
  "doc_474": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_202/doc_474.pdf",
  "doc_476": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_203/doc_476.pdf",
  "doc_477": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_203/doc_477.pdf",
  "doc_479": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_203/doc_479.pdf",
  "doc_480": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_203/doc_480.pdf",
  "doc_482": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_203/doc_482.pdf",
  "doc_483": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_203/doc_483.pdf",
  "doc_484": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_203/doc_484.pdf",
  "doc_617": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_247/doc_617.pdf",
  "doc_618": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_247/doc_618.pdf",
  "doc_620": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_247/doc_620.pdf",
  "doc_621": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_247/doc_621.pdf",
  "doc_622": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_247/doc_622.pdf",
  "doc_624": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_248/doc_624.pdf",
  "doc_625": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_249/doc_625.pdf",
  "doc_627": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_249/doc_627.pdf",
  "doc_628": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_250/doc_628.pdf",
  "doc_629": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_251/doc_629.pdf",
  "doc_631": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_252/doc_631.pdf",
  "doc_632": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_252/doc_632.pdf",
  "doc_634": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_252/doc_634.pdf",
  "doc_635": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_253/doc_635.pdf",
  "doc_636": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_254/doc_636.pdf",
  "doc_638": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_254/doc_638.pdf",
  "doc_639": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_255/doc_639.pdf",
  "doc_487": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_205/doc_487.pdf",
  "doc_488": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_205/doc_488.pdf",
  "doc_489": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_205/doc_489.pdf",
  "doc_491": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_206/doc_491.pdf",
  "doc_492": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_207/doc_492.pdf",
  "doc_494": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_208/doc_494.pdf",
  "doc_495": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_208/doc_495.pdf",
  "doc_497": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_209/doc_497.pdf",
  "doc_498": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_209/doc_498.pdf",
  "doc_499": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_209/doc_499.pdf",
  "doc_501": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_209/doc_501.pdf",
  "doc_502": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_210/doc_502.pdf",
  "doc_503": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_210/doc_503.pdf",
  "doc_505": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_211/doc_505.pdf",
  "doc_506": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_212/doc_506.pdf",
  "doc_508": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_212/doc_508.pdf",
  "doc_509": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_212/doc_509.pdf",
  "doc_511": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_212/doc_511.pdf",
  "doc_512": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_212/doc_512.pdf",
  "doc_513": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_212/doc_513.pdf",
  "doc_514": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_212/doc_514.pdf",
  "doc_516": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_214/doc_516.pdf",
  "doc_517": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_215/doc_517.pdf",
  "doc_519": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_215/doc_519.pdf",
  "doc_520": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_215/doc_520.pdf",
  "doc_523": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_215/doc_523.pdf",
  "doc_525": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_216/doc_525.pdf",
  "doc_526": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_216/doc_526.pdf",
  "doc_528": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_216/doc_528.pdf",
  "doc_529": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_216/doc_529.pdf",
  "doc_530": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_216/doc_530.pdf",
  "doc_532": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_217/doc_532.pdf",
  "doc_533": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_218/doc_533.pdf",
  "doc_534": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_218/doc_534.pdf",
  "doc_536": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_218/doc_536.pdf",
  "doc_537": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_218/doc_537.pdf",
  "doc_538": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_218/doc_538.pdf",
  "doc_641": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_256/doc_641.pdf",
  "doc_642": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_257/doc_642.pdf",
  "doc_644": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_258/doc_644.pdf",
  "doc_645": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_259/doc_645.pdf",
  "doc_646": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_259/doc_646.pdf",
  "doc_648": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_260/doc_648.pdf",
  "doc_649": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_260/doc_649.pdf",
  "doc_651": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_260/doc_651.pdf",
  "doc_652": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_260/doc_652.pdf",
  "doc_653": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_260/doc_653.pdf",
  "doc_655": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_260/doc_655.pdf",
  "doc_656": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_260/doc_656.pdf",
  "doc_658": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_262/doc_658.pdf",
  "doc_472": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_201/doc_472.pdf",
  "doc_475": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_203/doc_475.pdf",
  "doc_478": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_203/doc_478.pdf",
  "doc_481": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_203/doc_481.pdf",
  "doc_541": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_219/doc_541.pdf",
  "doc_543": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_219/doc_543.pdf",
  "doc_544": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_219/doc_544.pdf",
  "doc_546": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_219/doc_546.pdf",
  "doc_547": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_219/doc_547.pdf",
  "doc_549": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_220/doc_549.pdf",
  "doc_550": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_220/doc_550.pdf",
  "doc_551": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_220/doc_551.pdf",
  "doc_553": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_220/doc_553.pdf",
  "doc_554": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_220/doc_554.pdf",
  "doc_556": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_221/doc_556.pdf",
  "doc_557": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_221/doc_557.pdf",
  "doc_558": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_221/doc_558.pdf",
  "doc_560": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_221/doc_560.pdf",
  "doc_561": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_221/doc_561.pdf",
  "doc_660": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_263/doc_660.pdf",
  "doc_661": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_263/doc_661.pdf",
  "doc_663": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_265/doc_663.pdf",
  "doc_665": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_265/doc_665.pdf",
  "doc_666": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_265/doc_666.txt",
  "doc_668": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_266/doc_668.pdf",
  "doc_669": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_267/doc_669.pdf",
  "doc_562": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_222/doc_562.pdf",
  "doc_564": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_223/doc_564.pdf",
  "doc_565": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_223/doc_565.pdf",
  "doc_567": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_224/doc_567.pdf",
  "doc_568": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_225/doc_568.pdf",
  "doc_569": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_226/doc_569.pdf",
  "doc_571": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_228/doc_571.pdf",
  "doc_572": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_228/doc_572.pdf",
  "doc_574": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_230/doc_574.pdf",
  "doc_575": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_230/doc_575.pdf",
  "doc_576": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_231/doc_576.pdf",
  "doc_578": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_231/doc_578.pdf",
  "doc_579": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_231/doc_579.pdf",
  "doc_581": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_231/doc_581.pdf",
  "doc_582": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_231/doc_582.pdf",
  "doc_583": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_232/doc_583.pdf",
  "doc_585": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_234/doc_585.pdf",
  "doc_586": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_235/doc_586.pdf",
  "doc_588": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_235/doc_588.pdf",
  "doc_589": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_236/doc_589.pdf",
  "doc_591": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_236/doc_591.pdf",
  "doc_592": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_236/doc_592.pdf",
  "doc_593": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_236/doc_593.pdf",
  "doc_594": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_236/doc_594.pdf",
  "doc_596": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_238/doc_596.pdf",
  "doc_597": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_239/doc_597.pdf",
  "doc_616": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_247/doc_616.pdf",
  "doc_619": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_247/doc_619.pdf",
  "doc_623": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_248/doc_623.pdf",
  "doc_626": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_249/doc_626.pdf",
  "doc_630": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_252/doc_630.pdf",
  "doc_633": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_252/doc_633.pdf",
  "doc_637": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_254/doc_637.pdf",
  "doc_640": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_255/doc_640.pdf",
  "doc_485": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_204/doc_485.pdf",
  "doc_486": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_204/doc_486.pdf",
  "doc_490": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_206/doc_490.pdf",
  "doc_493": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_207/doc_493.pdf",
  "doc_496": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_208/doc_496.pdf",
  "doc_500": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_209/doc_500.pdf",
  "doc_504": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_211/doc_504.pdf",
  "doc_507": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_212/doc_507.pdf",
  "doc_510": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_212/doc_510.pdf",
  "doc_515": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_213/doc_515.pdf",
  "doc_518": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_215/doc_518.pdf",
  "doc_521": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_215/doc_521.pdf",
  "doc_522": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_215/doc_522.pdf",
  "doc_524": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_216/doc_524.pdf",
  "doc_527": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_216/doc_527.pdf",
  "doc_531": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_216/doc_531.pdf",
  "doc_535": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_218/doc_535.pdf",
  "doc_539": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_218/doc_539.pdf",
  "doc_643": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_257/doc_643.pdf",
  "doc_647": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_260/doc_647.pdf",
  "doc_650": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_260/doc_650.pdf",
  "doc_654": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_260/doc_654.pdf",
  "doc_657": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_261/doc_657.pdf",
  "doc_540": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_219/doc_540.pdf",
  "doc_542": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_219/doc_542.pdf",
  "doc_545": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_219/doc_545.pdf",
  "doc_548": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_220/doc_548.pdf",
  "doc_552": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_220/doc_552.pdf",
  "doc_555": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_220/doc_555.pdf",
  "doc_559": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_221/doc_559.pdf",
  "doc_659": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_262/doc_659.pdf",
  "doc_664": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_265/doc_664.txt",
  "doc_667": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_266/doc_667.pdf",
  "doc_563": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_222/doc_563.pdf",
  "doc_566": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_224/doc_566.pdf",
  "doc_570": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_227/doc_570.pdf",
  "doc_573": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_229/doc_573.pdf",
  "doc_577": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_231/doc_577.pdf",
  "doc_580": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_231/doc_580.pdf",
  "doc_584": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_233/doc_584.pdf",
  "doc_587": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_235/doc_587.pdf",
  "doc_590": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_236/doc_590.pdf",
  "doc_595": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_237/doc_595.pdf",
  "doc_662": "https://ccdr-explorer-bucket.s3.us-east-1.amazonaws.com/pub_264/doc_662.pdf"
}

DOCUMENT_CITATIONS = {
  "doc_598": "WBG, \"Ethiopia Country Climate and Development Report, February 2024\", 2024",
  "doc_599": "WBG, \"Ethiopia Country Climate and Development Report, February 2024\", 2024",
  "doc_600": "WBG, \"Zimbabwe Country Climate and Development Report\", 2024",
  "doc_601": "WBG, \"Lebanon Country Climate and Development Report\", 2024",
  "doc_602": "WBG, \"Liberia Country Climate Development Report\", 2024",
  "doc_603": "WBG, \"Liberia Country Climate Development Report\", 2024",
  "doc_604": "WBG, \"Maldives Country Climate and Development Report\", 2024",
  "doc_605": "WBG, \"Maldives Country Climate and Development Report\", 2024",
  "doc_606": "WBG, \"Maldives Country Climate and Development Report\", 2024",
  "doc_607": "WBG, \"Maldives Country Climate and Development Report\", 2024",
  "doc_608": "WBG, \"Western Balkans 6 Country Climate and Development Report\", 2024",
  "doc_609": "WBG, \"Western Balkans 6 Country Climate and Development Report\", 2024",
  "doc_610": "WBG, \"Western Balkans 6 Country Climate and Development Report\", 2024",
  "doc_611": "WBG, \"Western Balkans 6 Country Climate and Development Report\", 2024",
  "doc_612": "WBG, \"Western Balkans 6 Country Climate and Development Report\", 2024",
  "doc_613": "WBG, \"Western Balkans 6 Country Climate and Development Report\", 2024",
  "doc_614": "WBG, \"Western Balkans 6 Country Climate and Development Report\", 2024",
  "doc_615": "WBG, \"Ecuador Country Climate and Development Report\", 2024",
  "doc_473": "WBG, \"Angola Country Climate and Development Report\", 2022",
  "doc_474": "WBG, \"Cameroon Country Climate and Development Report\", 2022",
  "doc_476": "WBG, \"T\u00fcrkiye Country Climate and Development Report\", 2022",
  "doc_477": "WBG, \"T\u00fcrkiye Country Climate and Development Report\", 2022",
  "doc_479": "WBG, \"T\u00fcrkiye Country Climate and Development Report\", 2022",
  "doc_480": "WBG, \"T\u00fcrkiye Country Climate and Development Report\", 2022",
  "doc_482": "WBG, \"T\u00fcrkiye Country Climate and Development Report\", 2022",
  "doc_483": "WBG, \"T\u00fcrkiye Country Climate and Development Report\", 2022",
  "doc_484": "WBG, \"T\u00fcrkiye Country Climate and Development Report\", 2022",
  "doc_617": "WBG, \"Dominica, Grenada, Saint Lucia, and Saint Vincent and the Grenadines Country Climate And Development Report\", 2024",
  "doc_618": "WBG, \"Dominica, Grenada, Saint Lucia, and Saint Vincent and the Grenadines Country Climate And Development Report\", 2024",
  "doc_620": "WBG, \"Dominica, Grenada, Saint Lucia, and Saint Vincent and the Grenadines Country Climate And Development Report\", 2024",
  "doc_621": "WBG, \"Dominica, Grenada, Saint Lucia, and Saint Vincent and the Grenadines Country Climate And Development Report\", 2024",
  "doc_622": "WBG, \"Dominica, Grenada, Saint Lucia, and Saint Vincent and the Grenadines Country Climate And Development Report\", 2024",
  "doc_624": "WBG, \"The Pacific Atoll Countries Country Climate and Development Report\", 2024",
  "doc_625": "WBG, \"Mongolia Country Climate and Development Report\", 2024",
  "doc_627": "WBG, \"Mongolia Country Climate and Development Report\", 2024",
  "doc_628": "WBG, \"Guinea-Bissau Country Climate and Development Report\", 2024",
  "doc_629": "WBG, \"Central African Republic Country Climate and Development Report\", 2024",
  "doc_631": "WBG, \"Madagascar Country Climate and Development Report\", 2024",
  "doc_632": "WBG, \"Madagascar Country Climate and Development Report\", 2024",
  "doc_634": "WBG, \"Madagascar Country Climate and Development Report\", 2024",
  "doc_635": "WBG, \"Poland Country Climate and Development Report\", 2024",
  "doc_636": "WBG, \"Senegal Country Climate and Development Report\", 2024",
  "doc_638": "WBG, \"Senegal Country Climate and Development Report\", 2024",
  "doc_639": "WBG, \"Tajikistan Country Climate and Development Report\", 2024",
  "doc_487": "WBG, \"Vietnam Country Climate and Development Report\", 2022",
  "doc_488": "WBG, \"Vietnam Country Climate and Development Report\", 2022",
  "doc_489": "WBG, \"Vietnam Country Climate and Development Report\", 2022",
  "doc_491": "WBG, \"Rwanda Country Climate and Development Report\", 2022",
  "doc_492": "WBG, \"Nepal Country Climate and Development Report\", 2022",
  "doc_494": "WBG, \"Morocco Country Climate and Development Report\", 2022",
  "doc_495": "WBG, \"Morocco Country Climate and Development Report\", 2022",
  "doc_497": "WBG, \"Bangladesh Country Climate and Development Report\", 2022",
  "doc_498": "WBG, \"Bangladesh Country Climate and Development Report\", 2022",
  "doc_499": "WBG, \"Bangladesh Country Climate and Development Report\", 2022",
  "doc_501": "WBG, \"Bangladesh Country Climate and Development Report\", 2022",
  "doc_502": "WBG, \"South Africa Country Climate and Development Report\", 2022",
  "doc_503": "WBG, \"South Africa Country Climate and Development Report\", 2022",
  "doc_505": "WBG, \"China Country Climate and Development Report\", 2022",
  "doc_506": "WBG, \"Malawi Country Climate and Development Report\", 2022",
  "doc_508": "WBG, \"Malawi Country Climate and Development Report\", 2022",
  "doc_509": "WBG, \"Malawi Country Climate and Development Report\", 2022",
  "doc_511": "WBG, \"Malawi Country Climate and Development Report\", 2022",
  "doc_512": "WBG, \"Malawi Country Climate and Development Report\", 2022",
  "doc_513": "WBG, \"Malawi Country Climate and Development Report\", 2022",
  "doc_514": "WBG, \"Malawi Country Climate and Development Report\", 2022",
  "doc_516": "WBG, \"Jordan Country Climate and Development Report\", 2022",
  "doc_517": "WBG, \"Pakistan Country Climate and Development Report\", 2022",
  "doc_519": "WBG, \"Pakistan Country Climate and Development Report\", 2022",
  "doc_520": "WBG, \"Pakistan Country Climate and Development Report\", 2022",
  "doc_523": "WBG, \"Pakistan Country Climate and Development Report\", 2022",
  "doc_525": "WBG, \"Peru Country Climate and Development Report\", 2022",
  "doc_526": "WBG, \"Peru Country Climate and Development Report\", 2022",
  "doc_528": "WBG, \"Peru Country Climate and Development Report\", 2022",
  "doc_529": "WBG, \"Peru Country Climate and Development Report\", 2022",
  "doc_530": "WBG, \"Peru Country Climate and Development Report\", 2022",
  "doc_532": "WBG, \"Iraq Country Climate and Development Report\", 2022",
  "doc_533": "WBG, \"Argentina Country Climate and Development Report\", 2022",
  "doc_534": "WBG, \"Argentina Country Climate and Development Report\", 2022",
  "doc_536": "WBG, \"Argentina Country Climate and Development Report\", 2022",
  "doc_537": "WBG, \"Argentina Country Climate and Development Report\", 2022",
  "doc_538": "WBG, \"Argentina Country Climate and Development Report\", 2022",
  "doc_641": "WBG, \"Moldova Country Climate and Development Report\", 2024",
  "doc_642": "WBG, \"Armenia Country Climate and Development Report\", 2024",
  "doc_644": "WBG, \"Djibouti Country Climate and Development Report\", 2024",
  "doc_645": "WBG, \"Yemen Country Climate and Development Report\", 2024",
  "doc_646": "WBG, \"Yemen Country Climate and Development Report\", 2024",
  "doc_648": "WBG, \"Tanzania Country Climate and Development Report\", 2024",
  "doc_649": "WBG, \"Tanzania Country Climate and Development Report\", 2024",
  "doc_651": "WBG, \"Tanzania Country Climate and Development Report\", 2024",
  "doc_652": "WBG, \"Tanzania Country Climate and Development Report\", 2024",
  "doc_653": "WBG, \"Tanzania Country Climate and Development Report\", 2024",
  "doc_655": "WBG, \"Tanzania Country Climate and Development Report\", 2024",
  "doc_656": "WBG, \"Tanzania Country Climate and Development Report\", 2024",
  "doc_658": "WBG, \"Tajikistan Country Climate and Development Report\", 2025",
  "doc_472": "WBG, \"Angola Country Climate and Development Report\", 2022",
  "doc_475": "WBG, \"T\u00fcrkiye Country Climate and Development Report\", 2022",
  "doc_478": "WBG, \"T\u00fcrkiye Country Climate and Development Report\", 2022",
  "doc_481": "WBG, \"T\u00fcrkiye Country Climate and Development Report\", 2022",
  "doc_541": "WBG, \"Philippines Country Climate and Development Report\", 2022",
  "doc_543": "WBG, \"Philippines Country Climate and Development Report\", 2022",
  "doc_544": "WBG, \"Philippines Country Climate and Development Report\", 2022",
  "doc_546": "WBG, \"Philippines Country Climate and Development Report\", 2022",
  "doc_547": "WBG, \"Philippines Country Climate and Development Report\", 2022",
  "doc_549": "WBG, \"Kazakhstan Country Climate and Development Report\", 2022",
  "doc_550": "WBG, \"Kazakhstan Country Climate and Development Report\", 2022",
  "doc_551": "WBG, \"Kazakhstan Country Climate and Development Report\", 2022",
  "doc_553": "WBG, \"Kazakhstan Country Climate and Development Report\", 2022",
  "doc_554": "WBG, \"Kazakhstan Country Climate and Development Report\", 2022",
  "doc_556": "WBG, \"Egypt Country Climate and Development Report\", 2022",
  "doc_557": "WBG, \"Egypt Country Climate and Development Report\", 2022",
  "doc_558": "WBG, \"Egypt Country Climate and Development Report\", 2022",
  "doc_560": "WBG, \"Egypt Country Climate and Development Report\", 2022",
  "doc_561": "WBG, \"Egypt Country Climate and Development Report\", 2022",
  "doc_660": "WBG, \"Togo Country Climate and Development Report\", 2025",
  "doc_661": "WBG, \"Togo Country Climate and Development Report\", 2025",
  "doc_663": "WBG, \"Comoros Country Climate and Development Report\", 2025",
  "doc_665": "WBG, \"Comoros Country Climate and Development Report\", 2025",
  "doc_666": "WBG, \"Comoros Country Climate and Development Report\", 2025",
  "doc_668": "WBG, \"Sri Lanka Country Climate and Development Report\", 2025",
  "doc_669": "WBG, \"Bhutan Country Climate and Development Report\", 2025",
  "doc_562": "WBG, \"Indonesia Country Climate and Development Report\", 2023",
  "doc_564": "WBG, \"Brazil Country Climate and Development Report\", 2023",
  "doc_565": "WBG, \"Brazil Country Climate and Development Report\", 2023",
  "doc_567": "WBG, \"Honduras Country Climate and Development Report\", 2023",
  "doc_568": "WBG, \"Mozambique Country Climate and Development Report\", 2023",
  "doc_569": "WBG, \"Colombia Country Climate and Development Report\", 2023",
  "doc_571": "WBG, \"Cambodia Country Climate and Development Report\", 2023",
  "doc_572": "WBG, \"Cambodia Country Climate and Development Report\", 2023",
  "doc_574": "WBG, \"C\u00f4te d\u2019Ivoire Country Climate and Development Report\", 2023",
  "doc_575": "WBG, \"C\u00f4te d\u2019Ivoire Country Climate and Development Report\", 2023",
  "doc_576": "WBG, \"Kenya Country Climate and Development Report\", 2023",
  "doc_578": "WBG, \"Kenya Country Climate and Development Report\", 2023",
  "doc_579": "WBG, \"Kenya Country Climate and Development Report\", 2023",
  "doc_581": "WBG, \"Kenya Country Climate and Development Report\", 2023",
  "doc_582": "WBG, \"Kenya Country Climate and Development Report\", 2023",
  "doc_583": "WBG, \"Democratic Republic of Congo (DRC) Country Climate and Development Report\", 2023",
  "doc_585": "WBG, \"Azerbaijan Country Climate and Development Report\", 2023",
  "doc_586": "WBG, \"Tunisia Country Climate and Development Report\", 2023",
  "doc_588": "WBG, \"Tunisia Country Climate and Development Report\", 2023",
  "doc_589": "WBG, \"Dominican Republic Country Climate and Development Report\", 2023",
  "doc_591": "WBG, \"Dominican Republic Country Climate and Development Report\", 2023",
  "doc_592": "WBG, \"Dominican Republic Country Climate and Development Report\", 2023",
  "doc_593": "WBG, \"Dominican Republic Country Climate and Development Report\", 2023",
  "doc_594": "WBG, \"Dominican Republic Country Climate and Development Report\", 2023",
  "doc_596": "WBG, \"MENA Country Climate and Development Report: Climate Change Action in the Middle East and North Africa \u2014 Key Insights from Country Climate and Development Reports\", 2023",
  "doc_597": "WBG, \"Benin Country Climate and Development Report\", 2023",
  "doc_616": "WBG, \"Dominica, Grenada, Saint Lucia, and Saint Vincent and the Grenadines Country Climate And Development Report\", 2024",
  "doc_619": "WBG, \"Dominica, Grenada, Saint Lucia, and Saint Vincent and the Grenadines Country Climate And Development Report\", 2024",
  "doc_623": "WBG, \"The Pacific Atoll Countries Country Climate and Development Report\", 2024",
  "doc_626": "WBG, \"Mongolia Country Climate and Development Report\", 2024",
  "doc_630": "WBG, \"Madagascar Country Climate and Development Report\", 2024",
  "doc_633": "WBG, \"Madagascar Country Climate and Development Report\", 2024",
  "doc_637": "WBG, \"Senegal Country Climate and Development Report\", 2024",
  "doc_640": "WBG, \"Tajikistan Country Climate and Development Report\", 2024",
  "doc_485": "WBG, \"G5 Sahel Region Country Climate and Development Report\", 2022",
  "doc_486": "WBG, \"G5 Sahel Region Country Climate and Development Report\", 2022",
  "doc_490": "WBG, \"Rwanda Country Climate and Development Report\", 2022",
  "doc_493": "WBG, \"Nepal Country Climate and Development Report\", 2022",
  "doc_496": "WBG, \"Morocco Country Climate and Development Report\", 2022",
  "doc_500": "WBG, \"Bangladesh Country Climate and Development Report\", 2022",
  "doc_504": "WBG, \"China Country Climate and Development Report\", 2022",
  "doc_507": "WBG, \"Malawi Country Climate and Development Report\", 2022",
  "doc_510": "WBG, \"Malawi Country Climate and Development Report\", 2022",
  "doc_515": "WBG, \"Ghana Country Climate and Development Report\", 2022",
  "doc_518": "WBG, \"Pakistan Country Climate and Development Report\", 2022",
  "doc_521": "WBG, \"Pakistan Country Climate and Development Report\", 2022",
  "doc_522": "WBG, \"Pakistan Country Climate and Development Report\", 2022",
  "doc_524": "WBG, \"Peru Country Climate and Development Report\", 2022",
  "doc_527": "WBG, \"Peru Country Climate and Development Report\", 2022",
  "doc_531": "WBG, \"Peru Country Climate and Development Report\", 2022",
  "doc_535": "WBG, \"Argentina Country Climate and Development Report\", 2022",
  "doc_539": "WBG, \"Argentina Country Climate and Development Report\", 2022",
  "doc_643": "WBG, \"Armenia Country Climate and Development Report\", 2024",
  "doc_647": "WBG, \"Tanzania Country Climate and Development Report\", 2024",
  "doc_650": "WBG, \"Tanzania Country Climate and Development Report\", 2024",
  "doc_654": "WBG, \"Tanzania Country Climate and Development Report\", 2024",
  "doc_657": "WBG, \"Cabo Verde Country Climate and Development Report\", 2025",
  "doc_540": "WBG, \"Philippines Country Climate and Development Report\", 2022",
  "doc_542": "WBG, \"Philippines Country Climate and Development Report\", 2022",
  "doc_545": "WBG, \"Philippines Country Climate and Development Report\", 2022",
  "doc_548": "WBG, \"Kazakhstan Country Climate and Development Report\", 2022",
  "doc_552": "WBG, \"Kazakhstan Country Climate and Development Report\", 2022",
  "doc_555": "WBG, \"Kazakhstan Country Climate and Development Report\", 2022",
  "doc_559": "WBG, \"Egypt Country Climate and Development Report\", 2022",
  "doc_659": "WBG, \"Tajikistan Country Climate and Development Report\", 2025",
  "doc_664": "WBG, \"Comoros Country Climate and Development Report\", 2025",
  "doc_667": "WBG, \"Sri Lanka Country Climate and Development Report\", 2025",
  "doc_563": "WBG, \"Indonesia Country Climate and Development Report\", 2023",
  "doc_566": "WBG, \"Honduras Country Climate and Development Report\", 2023",
  "doc_570": "WBG, \"Republic of Congo Country Climate and Development Report - Diversifying Congo's Economy: Making the Most of Climate Change\", 2023",
  "doc_573": "WBG, \"Romania Country Climate and Development Report\", 2023",
  "doc_577": "WBG, \"Kenya Country Climate and Development Report\", 2023",
  "doc_580": "WBG, \"Kenya Country Climate and Development Report\", 2023",
  "doc_584": "WBG, \"Uzbekistan Country Climate and Development Report\", 2023",
  "doc_587": "WBG, \"Tunisia Country Climate and Development Report\", 2023",
  "doc_590": "WBG, \"Dominican Republic Country Climate and Development Report\", 2023",
  "doc_595": "WBG, \"West Bank and Gaza Country Climate and Development Report\", 2023",
  "doc_662": "WBG, \"Sierra Leone Country Climate and Development Report\", 2025"
}